#!/usr/bin/bash

#download and unzip .zip package
wget https://github.com/im1gr4nt/ginit/archive/refs/heads/master.zip
unzip master.zip


#create a bin directory in $HOME if it doesnt exist
if [ ! -d "$HOME/bin/" ]; then
	mkdir "$HOME/bin/"
else 
	:
fi

#check if path is correct -> ~/bin should be added 
if [[ echo $PATH | grep "$HOME/bin" ]]; then
	:
else
	export PATH="$HOME/bin:$PATH"

mv ./ginit-master/ginit $HOME/bin/

#remove unneccesary files  
rm -rf master.zip ginit-master
